name: Deploy

on:
  workflow_dispatch:
    inputs:
      envName:
        type: environment
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GLOBAL_NAME: github-actions-vars-${{ github.sha }}
  GLOBAL_NAME_REPEAT: $GLOBAL_NAME
  GLOBAL_SHORT_NAME: ${GLOBAL_NAME:0:7}
  # GLOBAL_BRANCH_NAME: ${{ github.ref##*/ }}
  GLOBAL_FULL_BRANCH_NAME: ${{ github.ref }}
  SHA: ${{ github.sha }}
  DELETED_BRANCH_PATH: ${{ github.event.ref }}
  # DELETED_BRANCH_NAME: ${{ github.event.ref##*/ }}
  PREFIX: 'refs/heads/'
  THE_REF: ${{ github.ref }}
  THE_HEAD_REF: ${{ github.head_ref }}
  REF_BRANCH: THE_REF#"$PREFIX"
  HEAD_REF_BRANCH: ${THE_HEAD_REF#"$PREFIX"}

jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Github Context Variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Echo Ref & Head Ref
        run: |
          echo "$THE_REF"
          echo "$THE_HEAD_REF"
          echo "$GLOBAL_NAME"
          echo "$GLOBAL_NAME_REPEAT"
          echo "$GLOBAL_SHORT_NAME"
          echo "$REF_BRANCH"
          echo ${THE_REF#"$PREFIX"}
          echo "$HEAD_REF_BRANCH"

  is-master:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.envName || 'Development' }}
    if: ${{ github.ref == 'refs/heads/master'}}
    steps:
      - name: env vars
        run: |
          echo "MY_SECRET_VALUE=${{ secrets.MY_SECRET_VALUE }}" >> $GITHUB_ENV
      - name: echo stuff
        run: |
          echo "Is master branch"
          [ "$MY_SECRET_VALUE" = "production" ] &&  echo prod || echo dev

  particular-branches:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/wonky'
    steps:
      - name: echo stuff
        run: |
          echo "Is specific branch"
          [ "$MY_SECRET_VALUE" = "production" ] &&  echo prod || echo dev
          echo $GLOBAL_FULL_BRANCH_NAME

  is-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    steps:
      - run: echo "event that triggered this workflow is push!"
      - run: echo $GLOBAL_FULL_BRANCH_NAME

  is-manual:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.envName || 'Development' }}
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: env vars
        run: |
          echo "MY_SECRET_VALUE=${{ secrets.MY_SECRET_VALUE }}" >> $GITHUB_ENV
      - name: echo stuff
        run: |
          echo "triggered manually!"
          [ "$MY_SECRET_VALUE" = "production" ] &&  echo prod || echo dev

  # followed tutorial: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: feckmore/github-actions-vars@v1
        with:
          who-to-greet: 'David'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - name: Only manually triggered
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "this was manually triggered"
      - name: Not manually triggered
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "this was NOT manually triggered"
