name: Push Info

on: push

env:
  GLOBAL_NAME: github-actions-vars-${{ github.sha }}
  GLOBAL_NAME_REPEAT: $GLOBAL_NAME
  GLOBAL_SHORT_NAME: ${GLOBAL_NAME:0:7}
  # GLOBAL_BRANCH_NAME: ${{ github.ref##*/ }}
  GLOBAL_FULL_BRANCH_NAME: ${{ github.ref }}
  SHA: ${{ github.sha }}
  DELETED_BRANCH_PATH: ${{ github.event.ref }}
  # DELETED_BRANCH_NAME: ${{ github.event.ref##*/ }}

jobs:
  is-master:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master'}}
    steps:
      - run: echo "Is master branch"

  is-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    steps:
      - run: echo "event that triggered this workflow is push!"

  # followed tutorial: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: feckmore/github-actions-vars@v1
        with:
          who-to-greet: 'David'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
