name: Deploy

on:
  workflow_dispatch:
    inputs:
      envName:
        type: environment
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GLOBAL_NAME: github-actions-vars-${{ github.sha }}
  GLOBAL_NAME_REPEAT: $GLOBAL_NAME
  GLOBAL_SHORT_NAME: ${GLOBAL_NAME:0:7}
  # GLOBAL_BRANCH_NAME: ${{ github.ref##*/ }}
  GLOBAL_FULL_BRANCH_NAME: ${{ github.ref }}
  SHA: ${{ github.sha }}
  DELETED_BRANCH_PATH: ${{ github.event.ref }}
  # DELETED_BRANCH_NAME: ${{ github.event.ref##*/ }}

jobs:
  is-master:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.envName || 'Development' }}
    if: ${{ github.ref == 'refs/heads/master'}}
    steps:
      - name: env vars
        run: |
          echo "MY_SECRET_VALUE=${{ secrets.MY_SECRET_VALUE }}" >> $GITHUB_ENV
      - name: echo stuff
        run: |
          echo "Is master branch"
          echo "$MY_SECRET_VALUE"

  is-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    steps:
      - run: echo "event that triggered this workflow is push!"

  is-manual:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.envName || 'Development' }}
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: env vars
        run: |
          echo "MY_SECRET_VALUE=${{ secrets.MY_SECRET_VALUE }}" >> $GITHUB_ENV
      - name: echo stuff
        run: |
          echo "triggered manually!"
          echo "$MY_SECRET_VALUE"

  # followed tutorial: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: feckmore/github-actions-vars@v1
        with:
          who-to-greet: 'David'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - name: Only manually triggered
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "this was manually triggered"
      - name: Not manually triggered
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "this was NOT manually triggered"
