name: Practicing with Variables

on: push

env:
  GLOBAL_NAME: github-actions-vars-${{ github.sha }}
  GLOBAL_NAME_REPEAT: $GLOBAL_NAME
  GLOBAL_SHORT_NAME: ${GLOBAL_NAME:0:7}
  # GLOBAL_BRANCH_NAME: ${{ github.ref##*/ }}
  GLOBAL_FULL_BRANCH_NAME: ${{ github.ref }}

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2

      - name: Step level variable
        run: echo Hello $WORLD_VALUE!
        env:
          WORLD_VALUE: world

      - name: Echo global variablea
        run: |
          echo $GLOBAL_NAME
          echo $GLOBAL_NAME_REPEAT
          echo $GLOBAL_SHORT_NAME
          echo $GLOBAL_BRANCH_NAME
          echo $GLOBAL_FULL_BRANCH_NAME

      - name: Parameter Expansion
        run: |
          SHORT_NAME = ${GLOBAL_NAME:0:7}
          echo $SHORT_NAME

      - name: Echo secret directly
        run: echo ${{ secrets.SUPER_SECRET }}

        # Works but hides secret in the dashboard "***"
      - name: Echo branch name directly
        run: |
          echo ${GITHUB_REF##*/}
          echo $GITHUB_REF

        # Returns the branch name successfully
      - name: Echo secret from env
        run: echo $SUPS
        env:
          SUPS: ${{ secrets.SUPER_SECRET }}

        # Works but hides secret in the dashboard "***"
      - name: Echo branch name from env
        run: echo $FULL_BRANCH_NAME
        env:
          FULL_BRANCH_NAME: $GITHUB_REF
        # FULL_BRANCH_NAME: $GITHUB_REF # Just returns string "$GITHUB_REF"
        #  BRANCH_NAME: ${ GITHUB_REF##*/ } # Just returns string: "${ GITHUB_REF##*/ }"
        #  BRANCH_NAME: ${{ GITHUB_REF##*/ }} # DOES NOT WORK ("unexpected symbol")
      - name: Step level variable from previous steps
        run: echo Hello $WORLD_VALUE!
