name: Practicing with Variables

on: push

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step level variable
        run: echo Hello $WORLD_VALUE!
        env:
          WORLD_VALUE: world

      - name: Echo secret directly
        run: echo ${{ secrets.SUPER_SECRET }}

        # Works but hides secret in the dashboard "***"
      - name: Echo secret, branch name directly
        run: echo ${GITHUB_REF##*/}

        # Returns the branch name successfully
      - name: Echo secret from env
        run: echo $SUPS
        env:
          SUPS: ${{ secrets.SUPER_SECRET }}

        # Works but hides secret in the dashboard "***"
      - name: Echo branch name from env
        run: echo $BRANCH_NAME
        env:
          FULL_BRANCH_NAME: $GITHUB_REF

        #  BRANCH_NAME: ${{ GITHUB_REF##*/ }} # DOES NOT WORK ("unexpected symbol")
      - name: Step level variable from previous steps
        run: echo Hello $WORLD_VALUE!
