name: Event Data

on: [create, delete, deployment, pull_request, push, release, workflow_dispatch]

env:
  GLOBAL_NAME: github-actions-vars-${{ github.sha }}
  GLOBAL_FULL_BRANCH_NAME: ${{ github.ref }}
  SHA: ${{ github.sha }}

jobs:
  variables-on-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/variables
